Vote api
A-APT/DuckBox-Android pull request #14
Opened 2022-04-11 02:53 UTC by mimwin

## 개요
- 투표 생성 API 연결

## 상세
- 시작시간을 현재 시간보다 1시간 이후로 설정하도록 수정하였습니다.
- `ViewModel`과 `ViewModelActivities` 를 사용하여 투표 생성 프래그먼트들의 데이터들을 액티비티에서도 쉽게 가져올 수 있도록 구현하였습니다.
- Retrofit 통신 과정에서 Date() 포맷을 서버와 동일하게 해주기 위해 `RetrofitClient.kt`에서 GsonBuilder()에 setDateFormat을 추가해주었습니다. ([참고](https://stackoverflow.com/questions/18473011/retrofit-gson-serialize-date-from-json-string-into-java-util-date))
- 좀 더 자세한 통신 로그를 보기 위해 `HttpLogginInterceptor`을 추가했습니다.

## 리뷰어가 확인할 사항

## 기타

2022-04-11 10:33 UTC, Hongji0611 requested changes
Date 이슈 정말 고생하셨습니다!!

- 저번 PR인데, fragment_create_vote_first.xml에서 상세 설명 TextView에 `android:inputType="textMultiLine"`이 있어서 글씨가 써집니다. 삭제해주세요!
- 다음 PR에서 홈이나 커뮤니티에서 `getAllVote` api도 연결해주세요~!

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/retrofit/interface/VoteInterface.kt
> +    @POST("/api/v1/vote/{groupId}")
GET 입니다!

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +        Toast.makeText(context, "현재 시간 1시간 이후로 설정해주세요.", Toast.LENGTH_SHORT).show()
checkNow에서 1시간 이후 설정하는 지 확인하는 코드가 없는 것 같습니다!

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateVoteActivity.kt
> +        voteRegisterDto.apply {
voteRegisterDto에 viewModel의 값을 넣는 이유가 궁금합니다!

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +    var title = ""
title, content는 지워도 될 것으로 보입니다!

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +                        val start = Calendar.getInstance()
start도 지워도 될 것으로 보입니다(아래쪽에 사용되는 곳이 없는 것 같아요)

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +                        val last = Calendar.getInstance()
위와 동일합니다~

2022-04-11 10:33 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +                    list[i].compress(Bitmap.CompressFormat.JPEG, 2, imageByteArray)
list[i]에 다시 안 넣어줘도 되나요?

2022-04-11 14:00 UTC, mimwin commented on app/src/main/java/com/AligatorAPT/DuckBox/view/fragment/createvote/CreateVoteFirstFragment.kt
> +                    list[i].compress(Bitmap.CompressFormat.JPEG, 2, imageByteArray)
bytearr 라는 ArrayList<ByteArray>를 새롭게 만들어서 거기에 list[i]의 compress 한 데이터를 넣어서 사용하는 방식입니다!

2022-04-11 14:00 UTC, mimwin commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateVoteActivity.kt
> +        voteRegisterDto.apply {
마지막 페이지에서 완료버튼을 누를때 activity에서 값들이 어떤지 출력해보는 용도였습니다! 지우도록 할게요

2022-04-11 17:39 UTC, mimwin reviewed
@Hongji0611 수정했습니다!

2022-04-12 00:36 UTC, Hongji0611 approved these changes

2022-04-12 01:03 UTC, merged