Vote detail api
A-APT/DuckBox-Android pull request #18
Opened 2022-05-03 12:05 UTC by mimwin

## 개요
- 투표 상세화면 API 연결

## 상세
- 남은 시간은 `x년x일x시간x분 남음` 으로 표시됩니다.
- 유권자 리스트에 포함되어 있지 않다면 투표를 확인할 수 없습니다. 
- collapsing layout의 height를 `match_parent`로 할 수 없어 `NestedScrollview`로 대체합니다.
- 투표를 생성하고 난 뒤 투표 상세 화면이 아닌 투표 리스트로 전환되도록 수정하였습니다.
- 후보 리스트 개수를 10개로 제한했습니다.

## 리뷰어가 확인할 사항
- 이미지를 불러오지 못하는 문제가 있습니다.
![image](https://user-images.githubusercontent.com/63101979/166448697-a7861154-ac5e-4d16-ba90-e15bdc312ab5.png)

## 기타
- 회원가입 / 로그인 후 테스트 해주세요.
- 투표장의 학번이 유권자 리스트에 포함되지 않았을 경우엔 유권자 리스트에 투표장의 학번을 추가하도록 했습니다. (다른 의견 있으시면 남겨주세요!)

2022-05-04 06:06 UTC, Hongji0611 requested changes
고생하셨습니다👍👍

투표장도 투표를 할 수 있는 권한이 있나요??
만약에 투표장은 투표에 참여 못한다면 유권자 리스트에 넣지 말고 투표 상세화면에 들어갈 때 투표장인지 확인하는 것을 넣는 게 좋을 것 같고,
투표장도 참여할 수 있다면 유권자 리스트에 넣는 게 좋은 것 같아요!

2022-05-04 06:06 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateVoteActivity.kt
> +        "","",false,"",Date(), Date(),ArrayList<ByteArray>(), "", ArrayList<String>(), null,false,false)
`title  = ""`
이런 형식으로 작성하는 게 값이 잘 들어갔는지 확인하기 좋을 것 같아요!

2022-05-04 06:06 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateVoteActivity.kt
> +    private var dispatcher: CoroutineDispatcher = Dispatchers.IO
dispatcher 사용되지 않는 것 같습니다!

2022-05-04 06:06 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/VoteDetailActivity.kt
> +        voteList = intent.getSerializableExtra("vote") as VoteDetailDto
이미지 크기가 커서 intent로 넘길 때 오류가 발생합니다! 그래서 viewmodel로 만들고, 싱글톤으로 해서 전역에서 접근 가능하도록 구현해야합니다!! (그룹리스트 viewmodel 참조)

2022-05-04 06:06 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/dialog/WriteDialog.kt
> +                dismiss()
startActivity() 이전에 dismiss()해야 실행되지 않나요?

2022-05-04 17:45 UTC, mimwin commented on app/src/main/java/com/AligatorAPT/DuckBox/view/dialog/WriteDialog.kt
> +                dismiss()
startActivity() 이후에 넣어도 나중에 intent가 끝나고 finish()가 되면 다시 되돌아와서 dismiss()를 실행시키기 때문에 잘 작동합니다!

2022-05-05 00:46 UTC, mimwin commented
투표 상세화면에 들어갈때 투표장인지 확인할 수 있는 방법은 현재로썬 닉네임을 통해 알 수 있습니다. 닉네임을 단말기기에서 가지고 있지 않아서 투표장의 학번을 유권자 리스트에 넣어서 확인하는 걸로 대체한 것입니다. 
투표장이 항상 투표할 권리가 있는건 아니니, 유권자 리스트에 0번째 학번이 투표장이고 그 이후로 실제 유권자 리스트가 존재하는걸로 하는건 어떤가요?

2022-05-09 00:12 UTC, Hongji0611 approved these changes

2022-05-09 00:12 UTC, merged