Survey
A-APT/DuckBox-Android pull request #21
Opened 2022-05-18 18:35 UTC by mimwin

## 개요
- 설문 생성 화면, 커스텀 다이얼로그

## 상세
![image](https://user-images.githubusercontent.com/63101979/169118368-98c737e9-8ebb-4dfd-aa33-478e748170a5.png)
- 위 이미지 상의 설문 생성 화면을 구현하였습니다.
- 설문 질문 가능 개수는 투표와 동일하게 최소 2개 최대 10개입니다.
- 투표와 설문 모두 왼쪽 드래그로 삭제만 가능하도록 변경하였습니다.
- 설문 생성의 첫번째, 세번째, 마지막 화면은 투표 생성 화면을 재활용했습니다.
- 투표와 설문 모두 생성하고 나면 투표/설문 리스트인 생성 전 화면으로 넘어갑니다. 
- 설문 생성까지 api를 연결하였습니다.

## 기타
- 객관식 옵션 추가 버튼에 배경색을 넣어 디자인이 변경되었습니다. 그 외에도 커스텀 다이얼로그 등 디자인 수정 사항이 있다면 알려주세요.
- 투표/설문 목록 보여주기, 상세보기 api 연결은 현재 작업 중입니다!

2022-05-19 16:08 UTC, Hongji0611 requested changes

2022-05-19 16:08 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/model/SurveyModel.kt
> +        RetrofitClient.SURVEY_INTERFACE_SERVICE.register(
RetrofitClient에 SURVEY_INTERFACE_SERVICE가 없습니다!

2022-05-19 16:08 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateSurveyActivity.kt
> +    lateinit var binding: ActivityPollCreateBinding
Activity 이름을 통일하는 게 좋을 것 같아요~

2022-05-19 16:08 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateSurveyActivity.kt
> +                viewModel.ownerPrivate.value = keyPair.privateKey.toString()
투표장(설문장)의 개인키는 투표나 설문을 생성할 때만 사용하고 필요 없는 값인가요?

2022-05-19 16:08 UTC, Hongji0611 commented on app/src/main/java/com/AligatorAPT/DuckBox/view/adapter/createsurvey/SurveySecondRVAdapter.kt
> +                    dialog.surveyListner = object: surveyTypeDialog.surveyDialogListener{
X 버튼 리스너도 추가해주세요!!

2022-05-19 16:08 UTC, Hongji0611 commented on app/src/main/res/layout/activity_poll_create.xml
> +        android:id="@+id/create_poll_close_iv"
X 버튼 setOnClickListener 추가해주세요!

2022-05-19 17:22 UTC, mimwin commented on app/src/main/java/com/AligatorAPT/DuckBox/view/activity/CreateSurveyActivity.kt
> +                viewModel.ownerPrivate.value = keyPair.privateKey.toString()
투표 및 설문을 생성할 때만 투표장(설문장)의 개인키를 생성하여 서버에 전달하게 되고, 서버가 해당 개인키를 이용해 OwnerSig를 생성하여 이후부턴 이를 사용합니다.

2022-05-20 01:25 UTC, Hongji0611 approved these changes
고생하셨습니다👍👍

2022-05-20 07:16 UTC, merged